### ISSUE TITLE
[1.12] Crash on game start

### ISSUE THREAD

**Issue by MasterEnderman** [Shadows-of-Fire/Singularities#2]
Forge: 14.23.2.2613
Placebo: 1.2.0
Singularities: 2.1.0
Avaritia: 3.2.0.13

Crash Report: https://pastebin.com/222WxH9Q

**Comment by Shadows-of-Fire** [comment]
Huh.  Thats weird.  That would mean theres an empty avaritia recipe that exists.  I'll add a check for the crash, but something strange is happening to cause it.

**Comment by Shadows-of-Fire** [comment]
Hopefully that fixes it, if it didn't, reopen this issue.

**Comment by MasterEnderman** [comment]
It doesn't crash anymore. Thank you for the fix.
