### ISSUE TITLE
Enchantment Glow Config Option

### ISSUE THREAD

**Issue by ghost** [Shadows-of-Fire/Singularities#3]
The suggestion is that in the section where you define the properties of the singularity (name, color1, color2, rarity, ID of singularity to apply effects to) there should be an option after the rarity for "enchantment glow" accepts value 0 or 1 where 0 is false and 1 is true, for example: 

A list of singularity definitions.  Order is name, color1, color2, rarity, glow.  String, integer, integer, integer, integer.  Rarity must be between 0 and 3 inclusive. Glow must be set to either 0 for false or 1 for true.
S:Singularities <|
ultimate core, 0x7fffff, 0xff7fed, 3, 1, 11
|>

**Comment by SextupleTap** [comment]
Wow so fucking lazy you cannot even give a response justifying why you don't want to add this...

**Comment by SextupleTap** [comment]
Is it that hard to want the singularity to have a fucking enchantment glow?
