### ISSUE TITLE
Custom singularities no recipes

### ISSUE THREAD

**Issue by YOYOK9** [Shadows-of-Fire/Singularities#7]
Hello, I made some custom singularities following the examples you had provided in the config file. However the 0-21 show the items in jei but have no recipe but 22+ have recipes. Not overly sure why this is happening. The game doesn't crash either. 

config: https://pastebin.com/q7YkJi35
Version: 1.12.2
Mod: Singularities-1.12.2-2.4.1
Avaritia: Avaritia-1.12.2-3.3.0.33-universal
Forge: 14.23.5.2854

**Comment by Shadows-of-Fire** [comment]
Because you haven't properly typed the oredict entries.  They're case sensitive.

**Comment by YOYOK9** [comment]
XD I feel stupid now, Thank you for the quick response. Cant believe I missed that.
